### PR TITLE
reenable-arch

### PR DESCRIPTION
**Pull request by ftalbrecht**

### CODE REVIEW

**Comment by ftalbrecht** [comment]
I forgot the place where I can reenable building of the arch images. Any hints, @renefritze?

**Comment by renefritze** [comment]
https://github.com/dune-community/Dockerfiles/blob/master/azure-pipelines.yml#L14 comment in those two lines.

**Comment by ftalbrecht** [comment]
Looks like [a codevov timeout](https://dev.azure.com/dune-community/dockerfiles/_build/results?buildId=1425&view=logs&jobId=908669ff-58f2-516b-abfb-7f01d947e9c3&j=908669ff-58f2-516b-abfb-7f01d947e9c3&t=9c0c8a9e-1e86-5b8e-8c01-3fd159994b50), do I just restart, @renefritze?

**Comment by renefritze** [comment]
@tobiasleibner actually found out that azure does that automagically itself

**Comment by renefritze** [comment]
But, yes, you can just restart too

**Comment by ftalbrecht** [comment]
Cant login to azure (github account/mail/microsoft trouble), job is not restarting. Could any of you try to, @renefritze @tobiasleibner ?

**Comment by tobiasleibner** [comment]
I also cannot restart the Pipeline. It does not restart automatically as it already did two attempts.

**Comment by renefritze** [comment]
Doesn't look like a transient error: https://dev.azure.com/dune-community/9ef71fb5-6b22-4a3f-9313-3c2efd06f20d/_apis/build/builds/1476/logs/17
I dimly remember @ftalbrecht showing me a fix for/error like this somewhere already though?

**Comment by ftalbrecht** [comment]
On 23.10.20 15:02, René Fritze wrote:
> Doesn't look like a transient error: https://dev.azure.com/dune-community/9ef71fb5-6b22-4a3f-9313-3c2efd06f20d/_apis/build/builds/1476/logs/17
> I dimly remember @ftalbrecht showing me a fix for/error like this somewhere already though?

Yes. The packages in the offending `pacman -S ...` command need to be
split and installed separately, depending on wether `yes | pacman -S
...` or `pacman -S --noconfirm ...` works. I should probably try to make
it work locally first....

**Comment by renefritze** [comment]
Moved to gitlab

**Pull request closed without merging**
