### PR TITLE
[debian-qtcreator] install paraview

### PR DESCRIPTION
**Pull request by ftalbrecht**

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Any idea what [this apt problem](https://dev.azure.com/dune-community/dockerfiles/_build/results?buildId=1320&view=logs&j=41f2a3f9-e2c2-50d2-1126-0dc859a1adb9&t=03f283af-64c1-5d2b-eca4-80efcbf2d65d&l=54) might be, @renefritze?

**Comment by renefritze** [comment]
No idea, sorry.

**Comment by renefritze** [comment]
You'll want to change the definition of APT_INSTALL/REDIRECT too maybe.

**Comment by ftalbrecht** [comment]
On 14.07.20 15:50, René Fritze wrote:
> You'll want to change the definition of APT_INSTALL/REDIRECT too maybe.

Any suggestions? Have not worked with apt for quite a while now...

**Comment by renefritze** [comment]
https://github.com/dune-community/Dockerfiles/blob/master/include/global_macros
Define redirect to empty string and remove the `q`s otherwise.

**Comment by ftalbrecht** [comment]
Ok, output is helping! :) Any ideas how to resolve [these](https://dev.azure.com/dune-community/dockerfiles/_build/results?buildId=1323&view=logs&j=41f2a3f9-e2c2-50d2-1126-0dc859a1adb9&t=03f283af-64c1-5d2b-eca4-80efcbf2d65d&l=1348), @renefritze? Its debian unstable which I do not use atm.

**Comment by renefritze** [comment]
I guess it would be nice if a makefile switch would be able to turn apt output on and off.

**Comment by renefritze** [comment]
Unstable no longer has clang-6. With backports the max we can go to for stable is 8. https://packages.debian.org/search?suite=buster-backports&searchon=names&keywords=clang-format

**Comment by renefritze** [comment]
And unstable also has 8 https://packages.debian.org/search?suite=sid&searchon=names&keywords=clang-format
So I guess that would be the one going forward, @dune-community/dune-xt-devs ?

**Comment by ftalbrecht** [comment]
> And unstable also has 8 https://packages.debian.org/search?suite=sid&searchon=names&keywords=clang-format
> So I guess that would be the one going forward, @dune-community/dune-xt-devs ?

Agreed. I will adapt the Docker images, but we will probably need to take a look at the diff between the clang-format-6 and clang-format-8 specs and adapt our config...

**Comment by ftalbrecht** [comment]
See https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-xt/-/issues/11

**Comment by renefritze** [comment]
So using 8 is no problem for the arch images either?

**Comment by ftalbrecht** [comment]
> So using 8 is no problem for the arch images either?

There we just install `clang` which is the most recent version. So I guess we've never use the same as with debian for quite some time now...

**Comment by renefritze** [comment]
Shouldn't that indicate that the config is pretty stable? Arch must at clang 10 for a while now, right?

**Comment by ftalbrecht** [comment]
It is, right. I was rather assuming that the arch images are not used anywhere... :)

**Comment by ftalbrecht** [comment]
I reverted the debug stuff, build before passed with clang-8. Ok with merging this when ready, or does the dune-xt/dune-gdt CI break down if we do?

**Comment by renefritze** [comment]
Maybe squash them all instead though?

CI should only possibly break after the CI images are recreated due a push in the super module.

**Comment by ftalbrecht** [comment]
> Maybe squash them all instead though?

Any reason apart from cosmetics?


> CI should only possibly break after the CI images are recreated due a push in the super module.

k

**Comment by renefritze** [comment]
> > Maybe squash them all instead though?
> 
> Any reason apart from cosmetics?
>

What do you mean _apart_ from :open_mouth: 
You can just drop them too btw, no need to squash even
.

**Comment by ftalbrecht** [comment]
I guess I just ignore the [codecov timeout](https://dev.azure.com/dune-community/dockerfiles/_build/results?buildId=1336&view=logs&j=908669ff-58f2-516b-abfb-7f01d947e9c3&t=9c0c8a9e-1e86-5b8e-8c01-3fd159994b50&l=474) and hope for the next build?

**Comment by renefritze** [comment]
Yeah, I guess :slightly_frowning_face: 

I checked now and the url was reachable again.

**Comment by ftalbrecht** [comment]
dropping the commits did not really seem to work, the debug output is still in there to be reverted...

**Comment by renefritze** [comment]
[This](https://github.com/dune-community/Dockerfiles/pull/71/commits) does not look like you dropped those commits.

**Comment by ftalbrecht** [comment]
> [This](https://github.com/dune-community/Dockerfiles/pull/71/commits) does not look like you dropped those commits.

See me note above...

**Comment by renefritze** [comment]
> dropping the commits did not really seem to work, the debug output is still in there to be reverted...

I read that as you having dropped the respective commits, but the output still happening for an unknown reason. Whereas the compare I linked shows that they have not been dropped. Maybe you forgot to push your branch again after the rebase?

**Comment by ftalbrecht** [comment]
No, by `there to be reverted` I meant that this still has to be done... :)

**Comment by ftalbrecht** [comment]
https://github.com/dune-community/Dockerfiles/pull/73

**Pull request merged**
