### PR TITLE
add numact

### PR DESCRIPTION
**Pull request by TiKeil**
We also need to make libtcmalloc available but libtcmalloc-minimal4 did not work yet

### CODE REVIEW

**Comment by renefritze** [comment]
How did tcmalloc not work yet?

**Comment by TiKeil** [comment]
Oh sorry that's confusing. Of course I managed to install it but it did not solve our purposes in the docker such that we do not need to add it here.

**Comment by renefritze** [comment]
Ah, ok then. So you can actually drop it from https://github.com/dune-community/Dockerfiles/pull/23/commits/9ede7a65aa3246f47afdb3afb4a7bff0c6412cc4 then?

**Comment by TiKeil** [comment]
I found the solution but the test fails. What did I do wrong here?

**Comment by ftalbrecht** [comment]
The problem reads
```
The push refers to repository [docker.io/dunecommunity/debian-unstable-minimal-interactive]
An image does not exist locally with the tag: dunecommunity/debian-unstable-minimal-interactive
```
Did you not change these tags to something else, @renefritze?

**Comment by renefritze** [comment]
Where did you get that message from, @ftalbrecht?
The actual problem is https://travis-ci.org/dune-community/Dockerfiles/jobs/457395279
Which isn't related to theses changes here at all, but rather some package renaming in debian-unstable I think.

**Comment by ftalbrecht** [comment]
> Where did you get that message from, @ftalbrecht?

Clicking on the `Details` of the `push`, then `debian_unstable_travis`...

**Comment by renefritze** [comment]
Right. Push doesn't happen on PR builds, which I only looked at. Same actual error though. I'm nerfing clang version for unstable now.

**Comment by renefritze** [comment]
Do you still want to add something here, or can this be merged, @TiKeil ?

**Comment by TiKeil** [comment]
No we can merge it.

**Pull request merged**
