### PR TITLE
[debian-interactive] install xterm

### PR DESCRIPTION
**Pull request by ftalbrecht**

### CODE REVIEW

**Comment by renefritze** [comment]
This would need a rebase on master to get the CI stuff working right again.

**Review by renefritze — COMMENTED** [review]
Is it necessary to have xterm in all the images sourcing the 'interactive' include? Could this be moved to the qtcreator image maybe?

**Comment by renefritze** [comment]
PIng @ftalbrecht

**Comment by ftalbrecht** [comment]
On 24.03.20 13:57, René Fritze wrote:
> PIng @ftalbrecht 

Can be closed, thx

**Pull request closed without merging**
