### PR TITLE
[testing] add ccache compression

### PR DESCRIPTION
**Pull request by tobiasleibner**

### CODE REVIEW

**Comment by renefritze** [comment]
Any idea how much of a speed/space tradeoff this compression is?

**Comment by tobiasleibner** [comment]
I did not measure performance, but I didn't notice a negative impact on compilation time and the ccache documentation states 
"...this may involve a tiny performance slowdown...". However, the compression is quite effective, cleaning the cache and compiling the functions tests in dune-xt resulted in a cache size well above 5 GB without compression and less than 1 GB with compression turned on if I recall correctly. Without compression, ccache with its default cache size of 5 GB was basically of no use for the functions tests, as the cache entries were discarded before being reused. With compression, the cache hit rate was 100% when no changes to the function test sources were made, as one would expect.

**Comment by renefritze** [comment]
Wow, that is impressive. Thanks!

**Comment by tobiasleibner** [comment]
I already added this to the ``dune-xt`` CI, see https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-xt/-/blob/master/.ci/gitlab/config.yml#L17. To be honest, I do not remember if adding this variable also to``testing/include/environment`` is actually required for dune-gdt or if that was only as a precaution.

**Comment by renefritze** [comment]
Baking the env setting into the image should be enough, yes.

**Pull request merged**
