### PR TITLE
[arch.full] install gcc-fortran

### PR DESCRIPTION
**Pull request by TiKeil**

### CODE REVIEW

**Comment by renefritze** [comment]
I guess this is obsolete and can be closed?

**Comment by ftalbrecht** [comment]
I'd rather have this, if arch starts to work again at some point. Any objections against merging this?

**Comment by renefritze** [comment]
> Any objections against merging this?

Not all. Would be great if it was rebased onto master rather than creating the merge commit though.

**Comment by renefritze** [comment]
This would need a rebase on master to get the CI right again.

**Comment by renefritze** [comment]
> This would need a rebase on master to get the CI right again.

Plus it's maybe also obsolete, being almost 2 years old?

**Comment by ftalbrecht** [comment]
On 24.03.20 13:56, René Fritze wrote:
>> This would need a rebase on master to get the CI right again.
> 
> Plus it's maybe also obsolete, being almost 2 years old?

Jup

**Comment by renefritze** [comment]
> On 24.03.20 13:56, René Fritze wrote: > This would need a rebase on master to get the CI right again. Plus it's maybe also obsolete, being almost 2 years old?
> Jup

Closing this then.

**Pull request closed without merging**
