### PR TITLE
Reenable arch

### PR DESCRIPTION
**Pull request by ftalbrecht**

### CODE REVIEW

**Comment by ftalbrecht** [comment]
I'll probably need to enable CI for arch somewhere, @renefritze?

**Comment by renefritze** [comment]
> I'll probably need to enable CI for arch somewhere, @renefritze?

https://github.com/dune-community/Dockerfiles/commit/e5d8d2a7e041efc41e70ab0d60ef3b12adfd45b7

**Comment by renefritze** [comment]
Once the build itself works, we should rebase this on the 'azure-arch' branch before merging into master.

**Comment by ftalbrecht** [comment]
Failure is in `testing` and `arch` subdir is still not build. So the latter I am still doing wrong, and the former is not my fault. :) Ideas, @renefritze

**Comment by ftalbrecht** [comment]
Ok, failure in testing is my fault, but probably also due to missing arch image generation.

**Comment by renefritze** [comment]
> Failure is in `testing` and `arch` subdir is still not build. So the latter I am still doing wrong, and the former is not my fault. :) Ideas, @renefritze

Yes:
> Once the build itself works, we should rebase this on the 'azure-arch' branch before merging into master.

Somewhere there was a commit that also disabled the arch subdir on travis.

**Comment by renefritze** [comment]
Is CMake weird in arch? https://dev.azure.com/dune-community/dockerfiles/_build/results?buildId=228

**Comment by ftalbrecht** [comment]
Not that I know of :/

I rebased on current master, but I am somehow a bit lost if I need to reenable arch somewhere (other than it being enabled in the azure pipeline definition).

If everything is enabled and the cmake stuff persists, I will have to look into that manually I guess..

**Comment by renefritze** [comment]
The `TestingImages` depends on all `DevImages *` being OK, that's why that is not built currently. `DevImages arch` just does `make arch` in the toplevel of the repo. So I think the CI should be doing everything you're doing locally, yes?

**Comment by renefritze** [comment]
Is this ready to merge now since the checks is ok? Do you want to squash some commits maybe?

**Pull request merged**
